### ISSUE TITLE
怎么获取图片文件？

### ISSUE THREAD

**Issue by wesleyck** [BoPang1996/Deep-RNN-Framework#1]
您好，非常感谢DeepRNN开源，请问下如何从ucf101提取图片文件呢？代码中的frame_size = 9 是什么意思呢？直接均匀从视频片段中采样9帧吗？还是随机采样9帧？采样数量和方式应该不同造成的结果也不一样吧？没在论文中看到说明，烦请赐教。还有silice_number = 7是什么意思呢？是一个视频片段切分7段的意思？新手勿喷，请赐教。谢谢~

**Comment by BoPang1996** [comment]
1. 视频提取图片：可以使用imageio库，可参考：https://www.programcreek.com/python/example/104521/imageio.get_reader

2. frame_size, slice_number 含义：模型使用了overlap coherence training scheme，将视频裁剪为有重叠的片段，frame_size是每个片段的帧的数量，slice_number 是片段的数量，具体取帧的方法可以自己确定，代码中的取法是按照一定的重叠比例（25%）均匀采样的。

**Comment by wesleyck** [comment]
> 1. 视频提取图片：可以使用imageio库，可参考：https://www.programcreek.com/python/example/104521/imageio.get_reader
> 2. frame_size, slice_number 含义：模型使用了overlap coherence training scheme，将视频裁剪为有重叠的片段，frame_size是每个片段的帧的数量，slice_number 是片段的数量，具体取帧的方法可以自己确定，代码中的取法是按照一定的重叠比例（25%）均匀采样的。

多谢~
