### ISSUE TITLE
训练时间过长

### ISSUE THREAD

**Issue by wesleyck** [BoPang1996/Deep-RNN-Framework#2]
你好，请问下默认的backbone supported model训练ucf101的时候有训练技巧吗？由于4卡1080ti显存限制，只能设置batch_size = 8，初步训练估计耗时300小时（epoch=30），请问下你们的设备大概什么配置耗时多久呢？有相关设置技巧吗？求赐教，谢谢~

**Comment by BoPang1996** [comment]
hi, 你可以尝试降低输入的分辨率，这个可以显著降低显存需求。另外，开源的代码中使用的多卡同步的batchnorm，这个开销比较大，可以选择使用pytorch官方的batchnorm，会有较大改善。

**Comment by wesleyck** [comment]
> hi, 你可以尝试降低输入的分辨率，这个可以显著降低显存需求。另外，开源的代码中使用的多卡同步的batchnorm，这个开销比较大，可以选择使用pytorch官方的batchnorm，会有较大改善。

谢谢回复，遇到一个很奇怪的问题，看了下论文中的表现在UCF上DeepRMB without BB为91.9显著好于15层RBM(with IncenptionV1)85.3, 但是在我们自己的数据集上表现分别为 85% 77%，跟您的实验结果相反，有相关建议吗？谢谢。（还有个小问题论文中的精度是map还是acc啊？谢谢~）

**Comment by BoPang1996** [comment]
那个91.9分是在Kinetics的预训练模型上调优的，Kinetics比UCF101数据大得多，然而那个85分是没有在kinetics上预训练的，遗憾的是，我们的实验并没有比较with and without BB的模型的精度差异。 另，精度是acc，没有采用map，不同数据集的类别分布不是很均等，用map不太直观。

**Comment by wesleyck** [comment]
> 那个91.9分是在Kinetics的预训练模型上调优的，Kinetics比UCF101数据大得多，精度是acc，没有采用map，不同数据集的类别分布不是很均等，用map不太直观。

谢谢回复~我再去研究研究代码，能否方便留下邮箱日后不懂的请教你，谢谢

**Comment by BoPang1996** [comment]
论文中邮箱即可。
